package com.example.airport.myBatis.model;

public class Pilot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.FIRST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    private String identificationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.LAST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOT.AIRLINE_ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    private Long airlineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.ID
     *
     * @return the value of PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.ID
     *
     * @param id the value for PUBLIC.PILOT.ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.FIRST_NAME
     *
     * @return the value of PUBLIC.PILOT.FIRST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.PILOT.FIRST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.IDENTIFICATION_NUMBER
     *
     * @return the value of PUBLIC.PILOT.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public String getIdentificationNumber() {
        return identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.IDENTIFICATION_NUMBER
     *
     * @param identificationNumber the value for PUBLIC.PILOT.IDENTIFICATION_NUMBER
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.LAST_NAME
     *
     * @return the value of PUBLIC.PILOT.LAST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.LAST_NAME
     *
     * @param lastName the value for PUBLIC.PILOT.LAST_NAME
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOT.AIRLINE_ID
     *
     * @return the value of PUBLIC.PILOT.AIRLINE_ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public Long getAirlineId() {
        return airlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOT.AIRLINE_ID
     *
     * @param airlineId the value for PUBLIC.PILOT.AIRLINE_ID
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    public void setAirlineId(Long airlineId) {
        this.airlineId = airlineId;
    }
}