package com.example.airport.myBatis.dao;

import com.example.airport.myBatis.model.Airline;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AirlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int insert(Airline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    Airline selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    List<Airline> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRLINE
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int updateByPrimaryKey(Airline record);
}