package com.example.airport.myBatis.dao;

import com.example.airport.myBatis.model.Pilot;
import com.example.airport.myBatis.model.Plane;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface PilotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int insert(Pilot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    Pilot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    List<Pilot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Wed Mar 27 09:59:42 EET 2024
     */
    int updateByPrimaryKey(Pilot record);

    List<Pilot> findByAirline(Long airlineId);
}